### ISSUE TITLE
Error in bayes_opt_xgb

### ISSUE THREAD

**Issue by davidhbrann** [KordingLab/spykesML#3]
Hi, Thanks for this helpful notebook.

When I run bayes_opt_xgb, however, I keep getting the following error (in python2 and python3). It looks like the indentation and definition for xgb_new is incorrect.

<ipython-input-21-57beee0bda3f> in <module>()
----> 1 XGB_optimized, xgbBO_optimized = bayes_opt_xgb(X,y,num_iter=5)
      2 
      3 #Yt_hat, PR2 = fit_cv(X, y, algorithm = 'XGB_optimized', n_cv=10, verbose=1, label=[])

<ipython-input-20-a389e4fc80c0> in bayes_opt_xgb(X, y, xgbBO, num_iter)
     79 
     80     # This is the actual optimization method.
---> 81     xgbBO.maximize(init_points=init_points, n_iter=num_iter, xi=0.0)
     82     values = xgbBO.res['max']
     83     print(values)

/home/ratcontrol/py3env/local/lib/python3.5/site-packages/bayes_opt/bayesian_optimization.py in maximize(self, init_points, n_iter, acq, kappa, xi, **gp_params)
    247             if self.verbose:
    248                 self.plog.print_header()
--> 249             self.init(init_points)
    250 
    251         y_max = self.Y.max()

/home/ratcontrol/py3env/local/lib/python3.5/site-packages/bayes_opt/bayesian_optimization.py in init(self, init_points)
    102         for x in self.init_points:
    103 
--> 104             y_init.append(self.f(**dict(zip(self.keys, x))))
    105 
    106             if self.verbose:

<ipython-input-20-a389e4fc80c0> in xgb_evaluate(min_child_weight, colsample_bytree, max_depth, subsample, gamma, learning_rate, n_estimators)
     46             return Yt
     47 
---> 48         Yt_hat, PR2 = fit_cv(X_train, y_train, xgb_new, n_cv=6, verbose=0)
     49 
     50         return np.mean(PR2)

<ipython-input-6-aff7a7cdb6dd> in fit_cv(X, Y, algorithm, n_cv, verbose)
     42         Yt = Y[idx_t]
     43 
---> 44         Yt_hat = eval(algorithm)(Xr, Yr, Xt)
     45         Y_hat[idx_t] = Yt_hat
     46 

TypeError: eval() arg 1 must be a string, bytes or code object

**Comment by aribenjamin** [comment]
Hi, thanks for this tip! Rather than fix this up, we released a new notebook that is a tutorial for our nice and clean `MLencoding` class. In that notebook is a (cleaner) method for hyperparameter optimization. Recommend all interested use that method instead of this.

(Among other things, that one uses the `hyperopt` package, which I personally like better than this implementation of Bayesian optimization).
